import type { Problem, Submission } from "@/types";

export const problems: Problem[] = [
  {
    id: "1",
    slug: "two-sum",
    title: "Two Sum",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    acceptance: 54.2,
    description:
      "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.",
    constraints: [
      "2 <= nums.length <= 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "Only one valid answer exists.",
    ],
    examples: [
      { input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "nums[0] + nums[1] == 9" },
      { input: "nums = [3,2,4], target = 6", output: "[1,2]" },
    ],
    starterCode: {
      javascript: `function twoSum(nums, target) {\n  // Write your code here\n}`,
      python: `def two_sum(nums, target):\n    # Write your code here\n    pass`,
      cpp: `class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        \n    }\n};`,
    },
    testcases: [
      { id: "t1", input: "[2,7,11,15]\n9", output: "[0,1]" },
      { id: "t2", input: "[3,2,4]\n6", output: "[1,2]" },
      { id: "t3", input: "[3,3]\n6", output: "[0,1]", hidden: true },
    ],
  },
  {
    id: "2",
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "Easy",
    tags: ["String", "Stack"],
    acceptance: 41.0,
    description: "Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid.",
    constraints: ["1 <= s.length <= 10^4", "s consists of parentheses only."],
    examples: [
      { input: 's = "()"', output: "true" },
      { input: 's = "(]"', output: "false" },
    ],
    starterCode: {
      javascript: `function isValid(s) {\n  // Write your code here\n}`,
      python: `def is_valid(s):\n    pass`,
      cpp: `bool isValid(string s) {\n  \n}`,
    },
    testcases: [{ id: "t1", input: "()", output: "true" }],
  },
  {
    id: "3",
    slug: "longest-substring",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    tags: ["Hash Table", "Sliding Window"],
    acceptance: 34.8,
    description: "Given a string `s`, find the length of the longest substring without repeating characters.",
    constraints: ["0 <= s.length <= 5 * 10^4"],
    examples: [{ input: 's = "abcabcbb"', output: "3", explanation: 'The answer is "abc".' }],
    starterCode: {
      javascript: `function lengthOfLongestSubstring(s) {\n  \n}`,
      python: `def length_of_longest_substring(s):\n    pass`,
      cpp: `int lengthOfLongestSubstring(string s) {\n  \n}`,
    },
    testcases: [{ id: "t1", input: "abcabcbb", output: "3" }],
  },
  {
    id: "4",
    slug: "median-sorted-arrays",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    tags: ["Array", "Binary Search"],
    acceptance: 39.1,
    description: "Given two sorted arrays `nums1` and `nums2`, return the median of the two sorted arrays.",
    constraints: ["nums1.length == m", "nums2.length == n", "0 <= m, n <= 1000"],
    examples: [{ input: "nums1 = [1,3], nums2 = [2]", output: "2.0" }],
    starterCode: {
      javascript: `function findMedianSortedArrays(a, b) {\n  \n}`,
      python: `def find_median(a, b):\n    pass`,
      cpp: `double findMedian(vector<int>& a, vector<int>& b) {\n  \n}`,
    },
    testcases: [{ id: "t1", input: "[1,3]\n[2]", output: "2.0" }],
  },
  {
    id: "5",
    slug: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "Medium",
    tags: ["Array", "Sorting"],
    acceptance: 47.3,
    description: "Given an array of intervals, merge all overlapping intervals.",
    constraints: ["1 <= intervals.length <= 10^4"],
    examples: [{ input: "[[1,3],[2,6],[8,10]]", output: "[[1,6],[8,10]]" }],
    starterCode: {
      javascript: `function merge(intervals) {\n  \n}`,
      python: `def merge(intervals):\n    pass`,
      cpp: `vector<vector<int>> merge(vector<vector<int>>& intervals) {\n  \n}`,
    },
    testcases: [{ id: "t1", input: "[[1,3],[2,6],[8,10]]", output: "[[1,6],[8,10]]" }],
  },
  {
    id: "6",
    slug: "binary-tree-inorder",
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    tags: ["Tree", "DFS"],
    acceptance: 68.4,
    description: "Given the `root` of a binary tree, return the inorder traversal of its nodes' values.",
    constraints: ["The number of nodes in the tree is in the range [0, 100]."],
    examples: [{ input: "root = [1,null,2,3]", output: "[1,3,2]" }],
    starterCode: {
      javascript: `function inorderTraversal(root) {\n  \n}`,
      python: `def inorder(root):\n    pass`,
      cpp: `vector<int> inorderTraversal(TreeNode* root) {\n  \n}`,
    },
    testcases: [{ id: "t1", input: "[1,null,2,3]", output: "[1,3,2]" }],
  },
];

export const submissions: Submission[] = [
  { id: "s1", problemId: "1", problemTitle: "Two Sum", user: "alex@dev.io", language: "Python", status: "Accepted", runtime: "42 ms", submittedAt: "2m ago" },
  { id: "s2", problemId: "3", problemTitle: "Longest Substring", user: "jane@dev.io", language: "JS", status: "Wrong Answer", runtime: "—", submittedAt: "12m ago" },
  { id: "s3", problemId: "2", problemTitle: "Valid Parentheses", user: "kai@dev.io", language: "C++", status: "Accepted", runtime: "8 ms", submittedAt: "1h ago" },
  { id: "s4", problemId: "4", problemTitle: "Median Sorted Arrays", user: "li@dev.io", language: "Python", status: "TLE", runtime: "—", submittedAt: "3h ago" },
  { id: "s5", problemId: "5", problemTitle: "Merge Intervals", user: "mo@dev.io", language: "JS", status: "Accepted", runtime: "76 ms", submittedAt: "1d ago" },
  { id: "s6", problemId: "6", problemTitle: "Binary Tree Inorder", user: "sara@dev.io", language: "C++", status: "Runtime Error", runtime: "—", submittedAt: "2d ago" },
];
